// Breaking the Ice — 25-question icebreaker across 3 clusters.
// All questions are SCALE (1–10). No MC options.

export const BTI_SEED = {
  name: 'Breaking the Ice',
  description:
    'A lighthearted 25-question compatibility check across personality, social style, and daily habits. A great starting point before going deeper.',
  slug: 'breaking-the-ice',
  clusters: [
    { name: 'Personality & Energy', order_index: 0 },
    { name: 'Social Style & Communication', order_index: 1 },
    { name: 'Habits & Preferences', order_index: 2 },
  ],
  questions: [
    // ── CLUSTER 0: Personality & Energy (9 questions) ──────────────────
    {
      cluster_index: 0,
      order_index: 0,
      text: 'I am a morning person.',
      type: 'SCALE' as const,
      narrative_tags: ['energy', 'personality'],
      options: null,
    },
    {
      cluster_index: 0,
      order_index: 1,
      text: 'I laugh at my own jokes.',
      type: 'SCALE' as const,
      narrative_tags: ['personality', 'humor'],
      options: null,
    },
    {
      cluster_index: 0,
      order_index: 2,
      text: 'I recharge by spending time alone.',
      type: 'SCALE' as const,
      narrative_tags: ['introversion', 'energy'],
      options: null,
    },
    {
      cluster_index: 0,
      order_index: 3,
      text: 'I tend to trust people quickly.',
      type: 'SCALE' as const,
      narrative_tags: ['personality', 'trust'],
      options: null,
    },
    {
      cluster_index: 0,
      order_index: 4,
      text: 'I get way too competitive during games.',
      type: 'SCALE' as const,
      narrative_tags: ['personality', 'competitiveness'],
      options: null,
    },
    {
      cluster_index: 0,
      order_index: 5,
      text: "I don't stay angry for very long.",
      type: 'SCALE' as const,
      narrative_tags: ['emotional_register', 'personality'],
      options: null,
    },
    {
      cluster_index: 0,
      order_index: 6,
      text: 'I still feel like a kid sometimes.',
      type: 'SCALE' as const,
      narrative_tags: ['personality', 'playfulness'],
      options: null,
    },
    {
      cluster_index: 0,
      order_index: 7,
      text: 'I mostly finish what I start.',
      type: 'SCALE' as const,
      narrative_tags: ['habits', 'follow_through'],
      options: null,
    },
    {
      cluster_index: 0,
      order_index: 8,
      text: 'I sometimes apologize just to keep the peace.',
      type: 'SCALE' as const,
      narrative_tags: ['personality', 'conflict_avoidance'],
      options: null,
    },

    // ── CLUSTER 1: Social Style & Communication (8 questions) ───────────
    {
      cluster_index: 1,
      order_index: 0,
      text: 'I can make small talk with almost anyone.',
      type: 'SCALE' as const,
      narrative_tags: ['social', 'communication'],
      options: null,
    },
    {
      cluster_index: 1,
      order_index: 1,
      text: 'I sing along in the car when my favorite song comes on.',
      type: 'SCALE' as const,
      narrative_tags: ['personality', 'expressiveness'],
      options: null,
    },
    {
      cluster_index: 1,
      order_index: 2,
      text: 'I would rather listen than do most of the talking.',
      type: 'SCALE' as const,
      narrative_tags: ['social', 'communication'],
      options: null,
    },
    {
      cluster_index: 1,
      order_index: 3,
      text: 'I am usually the one who reaches out first.',
      type: 'SCALE' as const,
      narrative_tags: ['social', 'initiative'],
      options: null,
    },
    {
      cluster_index: 1,
      order_index: 4,
      text: "If someone cuts in line, I'll probably say something.",
      type: 'SCALE' as const,
      narrative_tags: ['social', 'assertiveness'],
      options: null,
    },
    {
      cluster_index: 1,
      order_index: 5,
      text: "I'd rather call someone than send a text.",
      type: 'SCALE' as const,
      narrative_tags: ['social', 'communication'],
      options: null,
    },
    {
      cluster_index: 1,
      order_index: 6,
      text: 'I remember little details that people tell me.',
      type: 'SCALE' as const,
      narrative_tags: ['social', 'attentiveness'],
      options: null,
    },
    {
      cluster_index: 1,
      order_index: 7,
      text: 'I usually have more tabs open than I need.',
      type: 'SCALE' as const,
      narrative_tags: ['habits', 'multitasking'],
      options: null,
    },

    // ── CLUSTER 2: Habits & Preferences (8 questions) ───────────────────
    {
      cluster_index: 2,
      order_index: 0,
      text: 'I usually arrive a few minutes early.',
      type: 'SCALE' as const,
      narrative_tags: ['habits', 'timeliness'],
      options: null,
    },
    {
      cluster_index: 2,
      order_index: 1,
      text: 'I return my shopping cart every time.',
      type: 'SCALE' as const,
      narrative_tags: ['habits', 'conscientiousness'],
      options: null,
    },
    {
      cluster_index: 2,
      order_index: 2,
      text: 'Being on time is a sign of respect.',
      type: 'SCALE' as const,
      narrative_tags: ['values', 'timeliness'],
      options: null,
    },
    {
      cluster_index: 2,
      order_index: 3,
      text: 'I make my bed almost every morning.',
      type: 'SCALE' as const,
      narrative_tags: ['habits', 'structure'],
      options: null,
    },
    {
      cluster_index: 2,
      order_index: 4,
      text: "I enjoy trying foods I've never had before.",
      type: 'SCALE' as const,
      narrative_tags: ['habits', 'openness'],
      options: null,
    },
    {
      cluster_index: 2,
      order_index: 5,
      text: 'My actual and documented tipping history proves I am a generous tipper.',
      type: 'SCALE' as const,
      narrative_tags: ['values', 'generosity'],
      options: null,
    },
    {
      cluster_index: 2,
      order_index: 6,
      text: 'I read the instructions before I start.',
      type: 'SCALE' as const,
      narrative_tags: ['habits', 'structure'],
      options: null,
    },
    {
      cluster_index: 2,
      order_index: 7,
      text: 'I check reviews before buying almost anything.',
      type: 'SCALE' as const,
      narrative_tags: ['habits', 'research'],
      options: null,
    },
  ],
}
