// Inner Compass — 30-question self-awareness set across 5 clusters.
// All questions are SCALE (1–10). No MC options.

export const IC_SEED = {
  name: 'Inner Compass',
  description:
    'A 30-question journey into decision-making, relationships, growth, risk, and meaning. Designed to surface how you think, what you value, and where you and your friend diverge.',
  slug: 'inner-compass',
  clusters: [
    { name: 'Decision Making', order_index: 0 },
    { name: 'Relationships', order_index: 1 },
    { name: 'Growth & Purpose', order_index: 2 },
    { name: 'Risk & Adaptability', order_index: 3 },
    { name: 'Meaning & Perspective', order_index: 4 },
  ],
  questions: [
    // ── CLUSTER 0: Decision Making (6 questions) ────────────────────────
    {
      cluster_index: 0,
      order_index: 0,
      text: 'I usually trust my gut over the data.',
      type: 'SCALE' as const,
      narrative_tags: ['intuition', 'decision_making'],
      options: null,
    },
    {
      cluster_index: 0,
      order_index: 1,
      text: "I've made decisions I knew were right that turned out to be wrong.",
      type: 'SCALE' as const,
      narrative_tags: ['decision_making', 'self_awareness'],
      options: null,
    },
    {
      cluster_index: 0,
      order_index: 2,
      text: 'I change my mind more often than people expect me to.',
      type: 'SCALE' as const,
      narrative_tags: ['flexibility', 'decision_making'],
      options: null,
    },
    {
      cluster_index: 0,
      order_index: 3,
      text: 'I usually decide quickly and adjust later rather than wait for more information.',
      type: 'SCALE' as const,
      narrative_tags: ['decision_making', 'action_bias'],
      options: null,
    },
    {
      cluster_index: 0,
      order_index: 4,
      text: "I've been told I overthink things.",
      type: 'SCALE' as const,
      narrative_tags: ['decision_making', 'rumination'],
      options: null,
    },
    {
      cluster_index: 0,
      order_index: 5,
      text: 'I enjoy being challenged more than being comfortable.',
      type: 'SCALE' as const,
      narrative_tags: ['growth', 'challenge_seeking'],
      options: null,
    },

    // ── CLUSTER 1: Relationships (6 questions) ──────────────────────────
    {
      cluster_index: 1,
      order_index: 0,
      text: 'I sometimes avoid difficult conversations longer than I should.',
      type: 'SCALE' as const,
      narrative_tags: ['relationships', 'conflict_avoidance'],
      options: null,
    },
    {
      cluster_index: 1,
      order_index: 1,
      text: "I need to be right more than I'd like to admit.",
      type: 'SCALE' as const,
      narrative_tags: ['relationships', 'ego'],
      options: null,
    },
    {
      cluster_index: 1,
      order_index: 2,
      text: "I find it harder to trust people after I've been let down once.",
      type: 'SCALE' as const,
      narrative_tags: ['trust', 'relationships'],
      options: null,
    },
    {
      cluster_index: 1,
      order_index: 3,
      text: 'I give people the benefit of the doubt even when my instincts say otherwise.',
      type: 'SCALE' as const,
      narrative_tags: ['trust', 'generosity'],
      options: null,
    },
    {
      cluster_index: 1,
      order_index: 4,
      text: 'I hold on to things longer than the other person realizes.',
      type: 'SCALE' as const,
      narrative_tags: ['relationships', 'emotional_processing'],
      options: null,
    },
    {
      cluster_index: 1,
      order_index: 5,
      text: 'I believe difficult conversations usually make relationships stronger.',
      type: 'SCALE' as const,
      narrative_tags: ['relationships', 'conflict', 'growth'],
      options: null,
    },

    // ── CLUSTER 2: Growth & Purpose (6 questions) ───────────────────────
    {
      cluster_index: 2,
      order_index: 0,
      text: 'I get restless when life feels too comfortable.',
      type: 'SCALE' as const,
      narrative_tags: ['growth', 'ambition'],
      options: null,
    },
    {
      cluster_index: 2,
      order_index: 1,
      text: "I've sacrificed something important chasing something bigger.",
      type: 'SCALE' as const,
      narrative_tags: ['ambition', 'trade_offs'],
      options: null,
    },
    {
      cluster_index: 2,
      order_index: 2,
      text: 'I compare myself to other people more than I want to.',
      type: 'SCALE' as const,
      narrative_tags: ['self_awareness', 'comparison'],
      options: null,
    },
    {
      cluster_index: 2,
      order_index: 3,
      text: 'I know what I want but struggle with how to get there.',
      type: 'SCALE' as const,
      narrative_tags: ['purpose', 'growth'],
      options: null,
    },
    {
      cluster_index: 2,
      order_index: 4,
      text: "I've walked away from money for something that mattered more.",
      type: 'SCALE' as const,
      narrative_tags: ['values', 'trade_offs'],
      options: null,
    },
    {
      cluster_index: 2,
      order_index: 5,
      text: 'I regularly question my own assumptions.',
      type: 'SCALE' as const,
      narrative_tags: ['self_awareness', 'intellectual_humility'],
      options: null,
    },

    // ── CLUSTER 3: Risk & Adaptability (6 questions) ────────────────────
    {
      cluster_index: 3,
      order_index: 0,
      text: "I've taken a risk that scared me and it paid off.",
      type: 'SCALE' as const,
      narrative_tags: ['risk', 'resilience'],
      options: null,
    },
    {
      cluster_index: 3,
      order_index: 1,
      text: "I've taken a risk that scared me and it didn't pay off.",
      type: 'SCALE' as const,
      narrative_tags: ['risk', 'failure'],
      options: null,
    },
    {
      cluster_index: 3,
      order_index: 2,
      text: "I'm better at starting things than finishing them.",
      type: 'SCALE' as const,
      narrative_tags: ['habits', 'follow_through'],
      options: null,
    },
    {
      cluster_index: 3,
      order_index: 3,
      text: 'When something goes wrong my first instinct is to figure out what I did.',
      type: 'SCALE' as const,
      narrative_tags: ['accountability', 'self_awareness'],
      options: null,
    },
    {
      cluster_index: 3,
      order_index: 4,
      text: "I've stayed in something too long because I didn't want to admit it wasn't working.",
      type: 'SCALE' as const,
      narrative_tags: ['risk', 'sunk_cost', 'self_awareness'],
      options: null,
    },
    {
      cluster_index: 3,
      order_index: 5,
      text: 'I try to understand people before judging them.',
      type: 'SCALE' as const,
      narrative_tags: ['empathy', 'relationships'],
      options: null,
    },

    // ── CLUSTER 4: Meaning & Perspective (6 questions) ──────────────────
    {
      cluster_index: 4,
      order_index: 0,
      text: "I've changed a strongly held belief because of something someone said.",
      type: 'SCALE' as const,
      narrative_tags: ['intellectual_humility', 'growth'],
      options: null,
    },
    {
      cluster_index: 4,
      order_index: 1,
      text: "I've hurt someone I cared about and still carry it.",
      type: 'SCALE' as const,
      narrative_tags: ['accountability', 'emotional_depth'],
      options: null,
    },
    {
      cluster_index: 4,
      order_index: 2,
      text: 'I measure success differently than most people in my life.',
      type: 'SCALE' as const,
      narrative_tags: ['values', 'meaning'],
      options: null,
    },
    {
      cluster_index: 4,
      order_index: 3,
      text: 'I believe most people are doing their best.',
      type: 'SCALE' as const,
      narrative_tags: ['empathy', 'perspective'],
      options: null,
    },
    {
      cluster_index: 4,
      order_index: 4,
      text: 'I believe my actions matter more than my intentions.',
      type: 'SCALE' as const,
      narrative_tags: ['values', 'accountability'],
      options: null,
    },
    {
      cluster_index: 4,
      order_index: 5,
      text: "I've been misunderstood by people who thought they knew me well.",
      type: 'SCALE' as const,
      narrative_tags: ['identity', 'relationships'],
      options: null,
    },
  ],
}
