// YYOSD — Yin Yang Operating System Diagnostic
// 50 questions across 7 clusters.
// MC options carry a pre-mapped `value` (1–10) for unified scoring.
// narrative_tags drive the template-based narrative engine.

export const YYOSD_SEED = {
  name: 'Yin Yang Operating System Diagnostic',
  description:
    'A structured analysis of operating system compatibility across 50 questions in seven clusters: epistemology, conflict architecture, justice, civilization, identity, politics, and relational diagnostics.',
  slug: 'yyosd',
  clusters: [
    { name: 'Truth, Reality & Epistemology', order_index: 0 },
    { name: 'Conflict Architecture', order_index: 1 },
    { name: 'Justice & Moral Tradeoffs', order_index: 2 },
    { name: 'Civilization & Collective Order', order_index: 3 },
    { name: 'Identity, Loyalty & Duty', order_index: 4 },
    { name: 'Politics as Downstream Expression', order_index: 5 },
    { name: 'Friendzi Core Diagnostics', order_index: 6 },
  ],
  questions: [
    // ── CLUSTER 1: Truth, Reality & Epistemology (Q1–Q7) ─────────────────
    {
      cluster_index: 0,
      order_index: 0,
      text: 'What is truth?',
      type: 'MC' as const,
      narrative_tags: ['epistemology', 'objectivism'],
      options: [
        { label: 'A', value: 9, description: 'Truth is objective — it exists independently of what anyone believes or feels.' },
        { label: 'B', value: 5, description: 'Truth is socially constructed — it reflects the consensus of a community at a given time.' },
        { label: 'C', value: 3, description: 'Truth is personal — each individual\'s reality is valid and cannot be fully judged by others.' },
        { label: 'D', value: 2, description: 'Truth is probabilistic — our best current approximations, always subject to revision.' },
      ],
    },
    {
      cluster_index: 0,
      order_index: 1,
      text: 'Who gets to determine what is true?',
      type: 'MC' as const,
      narrative_tags: ['epistemology', 'authority'],
      options: [
        { label: 'A', value: 9, description: 'Evidence, logic, and verifiable method — regardless of who holds power.' },
        { label: 'B', value: 6, description: 'Experts and credentialed institutions within their domains.' },
        { label: 'C', value: 4, description: 'Communities, through collective deliberation and consensus.' },
        { label: 'D', value: 1, description: 'Each individual, ultimately — no external authority overrides personal discernment.' },
      ],
    },
    {
      cluster_index: 0,
      order_index: 2,
      text: 'Human beings do not merely disagree about conclusions. They disagree about the processes through which conclusions become legitimate.',
      type: 'SCALE' as const,
      narrative_tags: ['epistemology', 'meta_disagreement'],
      options: null,
    },
    {
      cluster_index: 0,
      order_index: 3,
      text: 'Facts don\'t care about your feelings — and a civilization that forgets this eventually loses its ability to solve its own problems.',
      type: 'SCALE' as const,
      narrative_tags: ['rationalism', 'civilizational_health'],
      options: null,
    },
    {
      cluster_index: 0,
      order_index: 4,
      text: 'Feelings don\'t care about your facts — and a civilization that forgets this eventually loses its humanity and becomes a machine.',
      type: 'SCALE' as const,
      narrative_tags: ['emotional_register', 'civilizational_health'],
      options: null,
    },
    {
      cluster_index: 0,
      order_index: 5,
      text: 'Would you rather protect people from emotionally painful truths, or expose people to difficult truths even if some individuals become destabilized?',
      type: 'MC' as const,
      narrative_tags: ['truth_ethics', 'paternalism'],
      options: [
        { label: 'A', value: 2, description: 'Protect — emotional and social stability have real value; painful truths must be carefully managed.' },
        { label: 'B', value: 8, description: 'Expose — truth is foundational; protecting people from it is a form of disrespect.' },
        { label: 'C', value: 5, description: 'It depends entirely on the relationship and the stakes involved.' },
        { label: 'D', value: 7, description: 'Expose, but with structure — truth requires timing, framing, and consent to be received well.' },
      ],
    },
    {
      cluster_index: 0,
      order_index: 6,
      text: 'Would you rather live with a painful but accurate understanding of reality, or maintain a partially inaccurate worldview that gives your life greater emotional stability and purpose?',
      type: 'MC' as const,
      narrative_tags: ['truth_ethics', 'emotional_register'],
      options: [
        { label: 'A', value: 9, description: 'Painful accuracy — I\'d rather know, regardless of cost.' },
        { label: 'B', value: 1, description: 'Functional illusion — stability and meaning matter more than perfect accuracy.' },
        { label: 'C', value: 6, description: 'I want accuracy AND meaning — and I don\'t believe they\'re mutually exclusive.' },
        { label: 'D', value: 5, description: 'It depends on what\'s at stake. Some truths are worth the destabilization; others aren\'t.' },
      ],
    },

    // ── CLUSTER 2: Conflict Architecture (Q8–Q16) ────────────────────────
    {
      cluster_index: 1,
      order_index: 0,
      text: 'Is conflict fundamentally:',
      type: 'MC' as const,
      narrative_tags: ['conflict_model'],
      options: [
        { label: 'A', value: 8, description: 'Diagnostic and clarifying — it reveals what\'s actually true about a relationship or system.' },
        { label: 'B', value: 2, description: 'Corrosive and destabilizing — it damages the trust and goodwill that relationships require.' },
        { label: 'C', value: 6, description: 'Both — it depends on how it\'s practiced and whether the parties have the tools to handle it.' },
        { label: 'D', value: 4, description: 'Depends — you can prevent most conflict with the right tools.' },
      ],
    },
    {
      cluster_index: 1,
      order_index: 1,
      text: 'Is discomfort more often:',
      type: 'MC' as const,
      narrative_tags: ['emotional_register', 'conflict_model'],
      options: [
        { label: 'A', value: 8, description: 'A sign of growth — discomfort is the price of expansion.' },
        { label: 'B', value: 2, description: 'A sign of decay — discomfort signals that something damaging is happening.' },
        { label: 'C', value: 5, description: 'A signal — it depends entirely on the nature and context.' },
        { label: 'D', value: 7, description: 'A sign of growth AND a signal — these aren\'t mutually exclusive; not everything good requires discomfort.' },
      ],
    },
    {
      cluster_index: 1,
      order_index: 2,
      text: 'Is emotional activation evidence that:',
      type: 'MC' as const,
      narrative_tags: ['emotional_register', 'conflict_model'],
      options: [
        { label: 'A', value: 7, description: 'Something important is happening — it should be treated as a direct signal to stop and re-evaluate.' },
        { label: 'B', value: 6, description: 'Something is being activated — and the activation itself is worth examining, regardless of what\'s actually happening.' },
        { label: 'C', value: 3, description: 'The person experiencing it needs support — regardless of whether harm is actually occurring.' },
        { label: 'D', value: 2, description: 'Nothing in particular — emotional activation is noise more often than signal.' },
      ],
    },
    {
      cluster_index: 1,
      order_index: 3,
      text: 'Is accountability fundamentally:',
      type: 'MC' as const,
      narrative_tags: ['accountability', 'relational_duty'],
      options: [
        { label: 'A', value: 9, description: 'Loving — to hold someone accountable is to take them seriously as a capable adult.' },
        { label: 'B', value: 5, description: 'Neutral — accountability isn\'t loving or hostile; it\'s a structured process.' },
        { label: 'C', value: 6, description: 'Context-dependent — it depends on the motive and method of the person applying it.' },
        { label: 'D', value: 3, description: 'Necessary but not loving — accountability is a function, not an expression of care.' },
      ],
    },
    {
      cluster_index: 1,
      order_index: 4,
      text: 'Should relationships prioritize:',
      type: 'MC' as const,
      narrative_tags: ['conflict_model', 'truth_ethics'],
      options: [
        { label: 'A', value: 9, description: 'Truth — relationships that can\'t handle honesty are structurally fragile.' },
        { label: 'B', value: 2, description: 'Harmony — preserving warmth and safety is foundational; skillful harmony is more durable.' },
        { label: 'C', value: 6, description: 'Both — truth and harmony are not in conflict when one or both parties lack relational skill.' },
        { label: 'D', value: 7, description: 'Both — truth and harmony are not in conflict when one or both parties are skilled enough.' },
      ],
    },
    {
      cluster_index: 1,
      order_index: 5,
      text: 'When truth and emotional safety conflict, should institutions prioritize:',
      type: 'MC' as const,
      narrative_tags: ['institutions', 'accountability', 'truth_ethics'],
      options: [
        { label: 'A', value: 9, description: 'Truth — institutions that suppress truth to protect feelings become corrupt.' },
        { label: 'B', value: 2, description: 'Emotional safety — institutions have a duty of care that limits how truth is deployed.' },
        { label: 'C', value: 7, description: 'Both — procedural legitimacy (due process, evidence standards, access to hearing) over both.' },
        { label: 'D', value: 8, description: 'Truth, but with structural protections that prevent the powerful from weaponizing it.' },
      ],
    },
    {
      cluster_index: 1,
      order_index: 6,
      text: 'Empathy without accountability is not a virtue. It is an obstacle to truth.',
      type: 'SCALE' as const,
      narrative_tags: ['accountability', 'emotional_register'],
      options: null,
    },
    {
      cluster_index: 1,
      order_index: 7,
      text: 'Boundaries — as currently practiced in most contexts — are frequently a socially acceptable mask for selfishness, avoidance, and cowardice.',
      type: 'SCALE' as const,
      narrative_tags: ['exit_ethics', 'consent_architecture'],
      options: null,
    },
    {
      cluster_index: 1,
      order_index: 8,
      text: 'Ghosting — the act of ending a relationship through silence and disappearance — is illegitimate except in cases involving genuine and documented safety risk.',
      type: 'SCALE' as const,
      narrative_tags: ['exit_ethics', 'relational_duty'],
      options: null,
    },

    // ── CLUSTER 3: Justice & Moral Tradeoffs (Q17–Q22) ───────────────────
    {
      cluster_index: 2,
      order_index: 0,
      text: 'Would you rather let nine guilty people walk free to prevent one wrongful conviction, or wrongly convict one innocent person to ensure nine guilty people are convicted?',
      type: 'MC' as const,
      narrative_tags: ['justice', 'due_process'],
      options: [
        { label: 'A', value: 8, description: 'Let the nine walk free — protecting the innocent is the foundational principle of justice; a wrongful conviction is an irreversible harm.' },
        { label: 'B', value: 3, description: 'Convict the one — if the nine are genuinely guilty, the social cost of freeing them is unacceptable.' },
        { label: 'C', value: 6, description: 'Neither — this framing exposes a flawed system; fix the system rather than accepting the tradeoff.' },
        { label: 'D', value: 5, description: 'It depends — on what the nine did and what the wrongful conviction would cost the innocent person.' },
      ],
    },
    {
      cluster_index: 2,
      order_index: 1,
      text: 'Would you rather allow one deeply offensive idea to circulate freely to prevent the government from deciding what ideas are acceptable, or suppress that idea even if it occasionally suppresses an important truth?',
      type: 'MC' as const,
      narrative_tags: ['free_speech', 'liberty'],
      options: [
        { label: 'A', value: 8, description: 'Allow the one — the cost of censorship is always higher than it appears.' },
        { label: 'B', value: 2, description: 'Suppress it — some ideas are so dangerous the social cost of allowing them outweighs the theoretical benefit.' },
        { label: 'C', value: 9, description: 'Allow all ideas + counter-speech — the solution to bad speech is more speech, not suppression.' },
        { label: 'D', value: 5, description: 'It depends — on who is doing the censoring and by what process.' },
      ],
    },
    {
      cluster_index: 2,
      order_index: 2,
      text: 'Would you rather preserve peace and social cohesion by leaving many past wrongs uncontested, or pursue full accountability even if it destabilizes relationships, institutions, or social order?',
      type: 'MC' as const,
      narrative_tags: ['accountability', 'justice'],
      options: [
        { label: 'A', value: 3, description: 'Preserve peace — uncontested records create stability; destabilized societies often cannot self-correct.' },
        { label: 'B', value: 8, description: 'Pursue accountability — peace without justice is just deferred conflict.' },
        { label: 'C', value: 6, description: 'Both — accountability and stability, properly sequenced, reinforce each other.' },
        { label: 'D', value: 5, description: 'It depends — on the scale of the injustice and the current stability of the system.' },
      ],
    },
    {
      cluster_index: 2,
      order_index: 3,
      text: 'What matters more:',
      type: 'MC' as const,
      narrative_tags: ['justice', 'fairness'],
      options: [
        { label: 'A', value: 9, description: 'Fairness — people should get what they actually deserve, consistently applied.' },
        { label: 'B', value: 2, description: 'Mercy — everyone\'s worst moment should not define their permanently classified worth.' },
        { label: 'C', value: 7, description: 'Both — fairness at scale, mercy for individuals; they reinforce rather than undercut each other.' },
        { label: 'D', value: 5, description: 'It depends — on the stakes; fairness if consequences are severe, mercy if moderate.' },
      ],
    },
    {
      cluster_index: 2,
      order_index: 4,
      text: 'Would you rather live in a society that too often forgives dangerous people, or one that too often punishes reformable people? Which failure is more costly?',
      type: 'MC' as const,
      narrative_tags: ['justice', 'accountability'],
      options: [
        { label: 'A', value: 3, description: 'Forgive too often — most forgiveness is a recoverable error; permanent confinement is not.' },
        { label: 'B', value: 7, description: 'Punish too often — the loss of reformation potential is a greater cost than the risk of re-offense.' },
        { label: 'C', value: 8, description: 'Punish too often — I\'d rather err on the side of protecting society than risk a repeat offense.' },
        { label: 'D', value: 5, description: 'It depends on what forgiveness means — forgiveness as failing vs. restored access are different questions.' },
      ],
    },
    {
      cluster_index: 2,
      order_index: 5,
      text: 'Would you rather have a close friend who is deeply loyal but sometimes dishonest, or one who is brutally honest but occasionally damages the relationship through uncompromising truthfulness?',
      type: 'MC' as const,
      narrative_tags: ['truth_ethics', 'loyalty', 'relational_duty'],
      options: [
        { label: 'A', value: 3, description: 'The loyal-but-dishonest friend — loyalty is the foundation; honesty without loyalty is unstable.' },
        { label: 'B', value: 7, description: 'The brutally honest friend — real friendship can survive truth; it cannot survive consistent dishonesty.' },
        { label: 'C', value: 9, description: 'Neither — a genuinely skilled friend can deliver truth with loyalty intact.' },
        { label: 'D', value: 5, description: 'It depends on the relationship depth and what the honesty is about.' },
      ],
    },

    // ── CLUSTER 4: Civilization & Collective Order (Q23–Q29) ─────────────
    {
      cluster_index: 3,
      order_index: 0,
      text: 'The needs of the many outweigh the needs of the few — or the one.',
      type: 'SCALE' as const,
      narrative_tags: ['justice', 'collectivism'],
      options: null,
    },
    {
      cluster_index: 3,
      order_index: 1,
      text: 'The needs and preferences of the majority should automatically override the needs and preferences of minorities in a democratic society.',
      type: 'SCALE' as const,
      narrative_tags: ['justice', 'collectivism', 'minority_rights'],
      options: null,
    },
    {
      cluster_index: 3,
      order_index: 2,
      text: 'Would you rather live in a society with significantly greater freedom even at the cost of occasional disorder, significantly greater equality even at the cost of individual freedom, or one that rewards earned excellence even at the cost of equality?',
      type: 'MC' as const,
      narrative_tags: ['liberty', 'meritocracy', 'civilizational_health'],
      options: [
        { label: 'A', value: 6, description: 'Freedom with disorder — a freer society produces more even when chaotic.' },
        { label: 'B', value: 3, description: 'Greater equality — a floor-focused civilization matters more than a ceiling.' },
        { label: 'C', value: 4, description: 'Greater equality, conditionally — if the floor is genuinely high enough.' },
        { label: 'D', value: 7, description: 'Excellence, conditionally — if earned, transparent, and non-trapping.' },
      ],
    },
    {
      cluster_index: 3,
      order_index: 3,
      text: 'What is more dangerous:',
      type: 'MC' as const,
      narrative_tags: ['civilizational_health', 'liberty'],
      options: [
        { label: 'A', value: 7, description: 'Tyranny — concentrated power corrodes and is harder to dislodge than chaos.' },
        { label: 'B', value: 3, description: 'Chaos — it destroys the conditions for any civilization to function.' },
        { label: 'C', value: 5, description: 'Both equally — both destroy civilization and are historically intertwined.' },
        { label: 'D', value: 4, description: 'It depends on the civilization\'s current stability and its primary current threat.' },
      ],
    },
    {
      cluster_index: 3,
      order_index: 4,
      text: 'Should civilization optimize more for:',
      type: 'MC' as const,
      narrative_tags: ['liberty', 'civilizational_health'],
      options: [
        { label: 'A', value: 8, description: 'Liberty — the capacity for self-determination as the precondition for everything else.' },
        { label: 'B', value: 4, description: 'Order — the precondition for trust, cooperation, and long-term thriving.' },
        { label: 'C', value: 6, description: 'Both — liberty and order reinforce each other in well-designed systems; the binary is false.' },
        { label: 'D', value: 5, description: 'It depends on where the civilization currently sits on the collapse-control spectrum.' },
      ],
    },
    {
      cluster_index: 3,
      order_index: 5,
      text: 'Can civilization survive without shared moral standards?',
      type: 'MC' as const,
      narrative_tags: ['civilizational_health', 'moral_standards'],
      options: [
        { label: 'A', value: 9, description: 'No — civilization is, by definition, a shared moral project. Without common standards it dissolves.' },
        { label: 'B', value: 2, description: 'Yes — procedural agreement on rules can substitute for moral consensus.' },
        { label: 'C', value: 5, description: 'Temporarily — but only if the procedural agreements are grounded in a shared foundational standard.' },
        { label: 'D', value: 4, description: 'It depends on what we mean by "survive" — functional stability vs. thriving are different standards.' },
      ],
    },
    {
      cluster_index: 3,
      order_index: 6,
      text: 'Would you rather live in a society with significantly greater equality of outcomes at the cost of lower overall innovation, or one with significantly higher inequality but dramatically higher innovation and more wide inequality of outcomes?',
      type: 'MC' as const,
      narrative_tags: ['meritocracy', 'justice', 'civilizational_health'],
      options: [
        { label: 'A', value: 3, description: 'Greater equality — a floor-focused civilization matters more than a ceiling above it.' },
        { label: 'B', value: 7, description: 'Higher ceiling — innovation and excellence create the conditions for broader prosperity.' },
        { label: 'C', value: 4, description: 'Greater equality, conditionally — if the floor is genuinely high enough.' },
        { label: 'D', value: 7, description: 'Excellence, conditionally — if the inequality is earned, regulated to feedback, and doesn\'t trap.' },
      ],
    },

    // ── CLUSTER 5: Identity, Loyalty & Duty (Q30–Q37) ────────────────────
    {
      cluster_index: 4,
      order_index: 0,
      text: 'What does it mean to be human?',
      type: 'MC' as const,
      narrative_tags: ['humanity', 'accountability', 'rationalism'],
      options: [
        { label: 'A', value: 9, description: 'To be capable of moral reasoning — and therefore accountable for choices.' },
        { label: 'B', value: 6, description: 'To experience consciousness — our self-awareness is what separates us from computation.' },
        { label: 'C', value: 4, description: 'To belong to a meaning-making community — we are defined by our narratives, not our biology.' },
        { label: 'D', value: 3, description: 'To love and be loved — our relational capacity is the defining feature of the species.' },
      ],
    },
    {
      cluster_index: 4,
      order_index: 1,
      text: 'What do human beings owe each other?',
      type: 'MC' as const,
      narrative_tags: ['relational_duty', 'humanity'],
      options: [
        { label: 'A', value: 3, description: 'Basic dignity — and nothing more beyond what is voluntarily agreed upon.' },
        { label: 'B', value: 7, description: 'Mutual obligation — we live in a structure of interdependence; baseline duties are not optional.' },
        { label: 'C', value: 5, description: 'It depends entirely on the relationship and the communities we\'ve built together.' },
        { label: 'D', value: 6, description: 'Whatever the relationship has earned — duty is proportional to relational investment.' },
      ],
    },
    {
      cluster_index: 4,
      order_index: 2,
      text: 'Do relationships generate duty beyond ongoing consent?',
      type: 'MC' as const,
      narrative_tags: ['relational_duty', 'consent_architecture'],
      options: [
        { label: 'A', value: 9, description: 'Yes — history creates obligations that survive any single act of withdrawal.' },
        { label: 'B', value: 1, description: 'No — consent is the source of all duty; exit is always available without breach.' },
        { label: 'C', value: 6, description: 'Yes, but with limits — some duty requires ongoing consent or has natural expiration.' },
        { label: 'D', value: 5, description: 'It depends on the type and depth — a 20-year marriage generates different duties than a 6-month friendship.' },
      ],
    },
    {
      cluster_index: 4,
      order_index: 3,
      text: 'All relationships are based on voluntary participation. There is no such thing as a duty that can be owed to a relationship.',
      type: 'SCALE' as const,
      narrative_tags: ['relational_duty', 'consent_architecture'],
      options: null,
    },
    {
      cluster_index: 4,
      order_index: 4,
      text: 'Would you sacrifice your own happiness to preserve your family relationships, or sacrifice your family relationships to pursue a more authentically fulfilling life?',
      type: 'MC' as const,
      narrative_tags: ['loyalty', 'duty', 'relational_duty'],
      options: [
        { label: 'A', value: 8, description: 'Sacrifice happiness — family is a foundational commitment that transcends personal fulfillment.' },
        { label: 'B', value: 3, description: 'Sacrifice the relationship — an inauthentic life damages everyone; real family love survives authenticity.' },
        { label: 'C', value: 5, description: 'The framing is a trap — authentic fulfillment and family obligation are not actually in conflict.' },
        { label: 'D', value: 6, description: 'It depends on what sacrifice means and whether the family relationships are themselves healthy.' },
      ],
    },
    {
      cluster_index: 4,
      order_index: 5,
      text: 'Is loyalty a virtue even when conditionally costly?',
      type: 'MC' as const,
      narrative_tags: ['loyalty', 'relational_duty'],
      options: [
        { label: 'A', value: 9, description: 'Yes — loyalty that costs nothing is not loyalty; real loyalty is demonstrated under pressure.' },
        { label: 'B', value: 6, description: 'Yes, but with limits — loyalty that enables harm to self or others is not virtuous.' },
        { label: 'C', value: 5, description: 'Yes, but calibrated — it should be assessed as a function, not held as an absolute moral quality.' },
        { label: 'D', value: 2, description: 'No — unconditional loyalty is a character flaw, not a virtue; all virtue has conditions.' },
      ],
    },
    {
      cluster_index: 4,
      order_index: 6,
      text: 'Would you rather belong to a tribe or institution that suppresses important parts of yourself, or be an outsider who expresses freely but risks social exclusion?',
      type: 'MC' as const,
      narrative_tags: ['identity', 'loyalty', 'free_speech'],
      options: [
        { label: 'A', value: 3, description: 'Belong — community is foundational; some self-suppression is the cost of belonging.' },
        { label: 'B', value: 7, description: 'Be an outsider — self-expression is non-negotiable; belonging without authenticity is imprisonment.' },
        { label: 'C', value: 8, description: 'Neither — I would build or find a community that tolerates the authentic self.' },
        { label: 'D', value: 5, description: 'It depends on what\'s being suppressed and what the tribe is actually providing.' },
      ],
    },
    {
      cluster_index: 4,
      order_index: 7,
      text: 'Should identity be:',
      type: 'MC' as const,
      narrative_tags: ['identity', 'epistemology'],
      options: [
        { label: 'A', value: 3, description: 'Protected — identity is the core of personhood and requires defense against external pressure.' },
        { label: 'B', value: 9, description: 'Stress-tested — identity built from honest challenge is more durable than protected identity.' },
        { label: 'C', value: 7, description: 'Both — protected from hostile attack but actively stress-tested from a position of security.' },
        { label: 'D', value: 5, description: 'Whatever the individual chooses — the goal is to move beyond fixed categories of identity.' },
      ],
    },

    // ── CLUSTER 6: Politics as Downstream Expression (Q38–Q45) ───────────
    {
      cluster_index: 5,
      order_index: 0,
      text: 'Multiculturalism as practiced in the West has failed structurally, not incidentally.',
      type: 'SCALE' as const,
      narrative_tags: ['multiculturalism', 'civilizational_health'],
      options: null,
    },
    {
      cluster_index: 5,
      order_index: 1,
      text: 'Immigration into Western nations should be significantly reduced until successful integration has occurred.',
      type: 'SCALE' as const,
      narrative_tags: ['immigration', 'civilizational_health'],
      options: null,
    },
    {
      cluster_index: 5,
      order_index: 2,
      text: 'America is dramatically better today than it was in the 1960s, and frameworks suggesting otherwise are either historically dishonest or clinically distorted.',
      type: 'SCALE' as const,
      narrative_tags: ['race', 'progress_narrative'],
      options: null,
    },
    {
      cluster_index: 5,
      order_index: 3,
      text: 'Patriotism can become a morally dangerous substitute for truth, and frameworks suggesting otherwise are either emotionally invested or willfully compromised.',
      type: 'SCALE' as const,
      narrative_tags: ['patriotism', 'epistemology'],
      options: null,
    },
    {
      cluster_index: 5,
      order_index: 4,
      text: 'Citizens should have the legal right to protest the American flag, including kneeling or refusing the Pledge of Allegiance.',
      type: 'SCALE' as const,
      narrative_tags: ['free_speech', 'patriotism'],
      options: null,
    },
    {
      cluster_index: 5,
      order_index: 5,
      text: 'I personally respect or approve of people who protest the American flag in those ways.',
      type: 'SCALE' as const,
      narrative_tags: ['patriotism', 'free_speech'],
      options: null,
    },
    {
      cluster_index: 5,
      order_index: 6,
      text: 'The Democratic Party in its current form represents a threat to free expression, institutional trust, and democratic norms.',
      type: 'SCALE' as const,
      narrative_tags: ['politics', 'free_speech'],
      options: null,
    },
    {
      cluster_index: 5,
      order_index: 7,
      text: 'The Republican Party in its current form represents a threat to democratic norms and constitutional stability.',
      type: 'SCALE' as const,
      narrative_tags: ['politics', 'institutions'],
      options: null,
    },

    // ── CLUSTER 7: Friendzi Core Diagnostics (Q46–Q50) ───────────────────
    {
      cluster_index: 6,
      order_index: 0,
      text: 'Most people dramatically over-allocate their Time, Treasure, and Talent to relationships that underperform, and dramatically under-allocate to relationships that over-deliver.',
      type: 'SCALE' as const,
      narrative_tags: ['relational_diagnostics', 'resource_allocation'],
      options: null,
    },
    {
      cluster_index: 6,
      order_index: 1,
      text: 'The primary cause of relational suffering is the unwillingness to classify people honestly at the level their behavior actually requires.',
      type: 'SCALE' as const,
      narrative_tags: ['relational_diagnostics', 'epistemology'],
      options: null,
    },
    {
      cluster_index: 6,
      order_index: 2,
      text: 'Compatibility is not sameness. Compatibility is the ability to metabolize difference without fracture or exit.',
      type: 'SCALE' as const,
      narrative_tags: ['relational_diagnostics', 'compatibility'],
      options: null,
    },
    {
      cluster_index: 6,
      order_index: 3,
      text: 'Shared beliefs do not guarantee shared reality-processing.',
      type: 'SCALE' as const,
      narrative_tags: ['relational_diagnostics', 'epistemology'],
      options: null,
    },
    {
      cluster_index: 6,
      order_index: 4,
      text: 'Thinking of the most important relationship in your life right now — can the two of you survive reality together?',
      type: 'MC' as const,
      narrative_tags: ['relational_diagnostics', 'compatibility'],
      options: [
        { label: 'A', value: 9, description: 'Yes — the operating systems are fundamentally compatible even when they differ.' },
        { label: 'B', value: 6, description: 'Conditionally — with significant structure we can metabolize the difference.' },
        { label: 'C', value: 4, description: 'Unsure — I have not yet fully stress-tested whether we survive difficult reality together.' },
        { label: 'D', value: 1, description: 'No — I see now that there are irreconcilable differences in how we process reality.' },
      ],
    },
  ],
}
